# Generated by Django 5.2.8 on 2025-11-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_solicitarfrete_freteiro_solicitarfrete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freteiro',
            name='cidade',
            field=models.CharField(default='Cascavel', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='data_nascimento',
            field=models.DateField(default='2005-05-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='estado',
            field=models.CharField(default='Paraná', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='tel',
            field=models.CharField(default='459999999999', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitarfrete',
            name='data_solicitacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitarfrete',
            name='freteiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.freteiro'),
        ),
        migrations.AlterField(
            model_name='solicitarfrete',
            name='hora_solicitacao',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default='2005-05-05'),
            preserve_default=False,
        ),
    ]
