# Generated by Django 5.2.8 on 2025-11-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_freteiro_cidade_alter_freteiro_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitarfrete',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
