# Generated by Django 5.2.8 on 2025-11-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_solicitarfrete_data_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitarfrete',
            name='hora_solicitacao',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
