# Generated by Django 5.2.8 on 2025-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_solicitarfrete_hora_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitarfrete',
            name='data_solicitacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitarfrete',
            name='hora_solicitacao',
            field=models.TimeField(),
        ),
    ]
