# Generated by Django 5.2.8 on 2025-11-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_solicitarfrete_data_solicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitarfrete',
            name='custo_frete',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solicitarfrete',
            name='distancia_km',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solicitarfrete',
            name='tempo_frete',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
