# Generated by Django 5.2.8 on 2025-11-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_solicitarfrete_custo_frete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitarfrete',
            name='tempo_frete',
        ),
    ]
