# Generated by Django 5.2.8 on 2025-11-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_solicitarfrete_tempo_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitarfrete',
            name='comprimento',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
